✋: add_sub;

add_sub 🤯 [int]:
    🤔 atom add_sub_cont{0}          { $val = $atom.val + $add_sub_cont.val; }
;

add_sub_cont 🤓[int a] 🤯 [int]:
    🤔 ADD atom add_sub_cont{a + 1}  { $val = $atom.val + $add_sub_cont.val; std::cout << a << std::endl; }
    🤔 SUB atom add_sub_cont{a + 1}  { $val = -$atom.val + $add_sub_cont.val; std::cout << a << std::endl; }
    🤔                               { $val = 0; std::cout << a << std::endl; }
;

mul 🤯[int]:
    🤔 atom mul_pow_cont{$atom.val}          { $val = $mul_pow_cont.val; }
;

mul_cont 🤓[int a] 🤯 [int]:
    🤔 MUL atom mul_pow_cont{a + 1}  { $val = $atom.val + $add_sub_cont.val; std::cout << a << std::endl; }
    🤔                               { $val = 0; std::cout << a << std::endl; }
;

pow 🤯[int]:
    🤔 atom pow_cont{$atom.val}          { $val = $mul_pow_cont.val; }
;

pow_cont 🤓[int a, int b] 🤯 [int]:
    🤔 MUL atom mul_pow_cont{a + 1}  { $val = $atom.val + $add_sub_cont.val; std::cout << a << std::endl; }
    🤔                               { $val = 0; std::cout << a << std::endl; }
;

atom 🤯 [int]:
    🤔 OPEN add_sub CLOSE            { $val = $add_sub.val; }
    🤔 NUM                           { $val = std::stoi($NUM.val); }
;

ADD: "\\+";
SUB: "\\-";
MUL: "\\*";
POW: "\\^";
OPEN: "\\(";
CLOSE: "\\)";
NUM: "\\d+";

👉: ' ' '\t' '\n' '\r';
